# -*- mode: ruby -*-
# vi: set ft=ruby :

load ("../../.chef/credentials.rb")
num_students = 2
image_slug = 'ubuntu-14-10-x64'

app_servers = num_students.times.map { |i| "student#{i}" }
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'digital_ocean'

Vagrant.configure('2') do |config|
    config.vm.provider :digital_ocean do |provider, override|
      provider.client_id = CREDENTIALS[:client_id]
      provider.api_key = CREDENTIALS[:api_key]
      provider.token = CREDENTIALS[:token]
      provider.image = image_slug
      provider.region = 'NYC3'
      provider.size = '512MB'
      provider.ssh_key_name = 'student@jetpackshark.com'
      override.ssh.private_key_path = '~/.ssh/class_rsa'
      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      provider.ca_path = "/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt"
    end
    app_servers.each do |srv| 
      config.vm.define srv  do |stud| 
        stud.vm.hostname = srv
      end
      config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = ['../../cookbooks']
        chef.roles_path = ['../../roles']
        chef.add_role "rails_class"
      end
    end
end